### ISSUE TITLE
native-image in the provided docker image fails in linker with `--enable-https`

### ISSUE THREAD

**Issue by rafaeldff** [graalvm/container#59]
Running native-image on any input, including a trivial hello world class, fails with `ld returned 1 exit status` if the `--enable-https` switch is included. The same input succeeds in my local instalation of graalvm.

My script to reproduce the issue:
```sh
#! /usr/bin/env bash

cat << EOF > Hello.java
public class Hello {
  public static void main(String[] args) {
    System.out.println("hello!");
  }
}
EOF

javac Hello.java

docker run -v $(pwd):/hello  --rm  --workdir /hello  -ti ghcr.io/graalvm/native-image:22   -cp . Hello  --enable-https
```

Which fails with the output:
```
===============================================================================================
GraalVM Native Image: Generating 'hello' (executable)...
===============================================================================================
[1/7] Initializing...                                                           (2.3s @ 0.20GB)
 Version info: 'GraalVM 22.1.0 Java 17 CE'
 C compiler: gcc (redhat, x86_64, 8.5.0)
 Garbage collector: Serial GC
[2/7] Performing analysis...  [[3.525s][warning][jni,resolve] Re-registering of platform native method: java.lang.PanwHooksNs.HookArgs0()V from code in a different classloader
[3.526s][warning][jni,resolve] Re-registering of platform native method: java.lang.PanwHooksNs.HookArgs1(Ljava/lang/Object;)V from code in a different classloader
[3.526s][warning][jni,resolve] Re-registering of platform native method: java.lang.PanwHooksNs.HookArgs2(Ljava/lang/Object;Ljava/lang/Object;)V from code in a different classloader
[3.526s][warning][jni,resolve] Re-registering of platform native method: java.lang.PanwHooksNs.HookArgs3(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)V from code in a different classloader
[3.526s][warning][jni,resolve] Re-registering of platform native method: java.lang.PanwHooksNs.HookArgs4(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)V from code in a different classloader
**************]                                 (18.2s @ 0.79GB)
   5,583 (85.83%) of  6,505 classes reachable
   7,476 (54.98%) of 13,598 fields reachable
  26,282 (55.24%) of 47,579 methods reachable
     350 classes,    96 fields, and 1,012 methods registered for reflection
      61 classes,    67 fields, and    54 methods registered for JNI access
[3/7] Building universe...                                                      (1.5s @ 1.22GB)
[4/7] Parsing methods...      [*]                                               (1.2s @ 1.75GB)
[5/7] Inlining methods...     [****]                                            (1.6s @ 1.48GB)
[6/7] Compiling methods...    [****]                                           (14.3s @ 1.56GB)
[7/7] Creating image...
                                                         (0.0s @ 2.19GB)
Fatal error: java.lang.RuntimeException: There was an error linking the native image: Linker command exited with 1

Linker command executed:
/usr/bin/gcc -z noexecstack -Wl,--gc-sections -Wl,--dynamic-list -Wl,/tmp/SVM-1043361363098864337/exported_symbols.list -Wl,--exclude-libs,ALL -Wl,-x -o /hello/hello hello.o /usr/lib64/graalvm/graalvm22-ce-java17/lib/svm/clibraries/linux-amd64/liblibchelper.a /usr/lib64/graalvm/graalvm22-ce-java17/lib/static/linux-amd64/glibc/libnet.a /usr/lib64/graalvm/graalvm22-ce-java17/lib/static/linux-amd64/glibc/libextnet.a /usr/lib64/graalvm/graalvm22-ce-java17/lib/static/linux-amd64/glibc/libnio.a /usr/lib64/graalvm/graalvm22-ce-java17/lib/static/linux-amd64/glibc/libjava.a /usr/lib64/graalvm/graalvm22-ce-java17/lib/static/linux-amd64/glibc/libfdlibm.a /usr/lib64/graalvm/graalvm22-ce-java17/lib/static/linux-amd64/glibc/libzip.a /usr/lib64/graalvm/graalvm22-ce-java17/lib/svm/clibraries/linux-amd64/libjvm.a -v -L/tmp/SVM-1043361363098864337 -L/usr/lib64/graalvm/graalvm22-ce-java17/lib/static/linux-amd64/glibc -L/usr/lib64/graalvm/graalvm22-ce-java17/lib/svm/clibraries/linux-amd64 -lpthread -ldl -lz -lrt

Linker command output:
Using built-in specs.
COLLECT_GCC=/usr/bin/gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/8/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,lto --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --enable-plugin --enable-initfini-array --with-isl --disable-libmpx --enable-offload-targets=nvptx-none --without-cuda-driver --enable-gnu-indirect-function --enable-cet --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 8.5.0 20210514 (Red Hat 8.5.0-4.0.2) (GCC)
COMPILER_PATH=/usr/libexec/gcc/x86_64-redhat-linux/8/:/usr/libexec/gcc/x86_64-redhat-linux/8/:/usr/libexec/gcc/x86_64-redhat-linux/:/usr/lib/gcc/x86_64-redhat-linux/8/:/usr/lib/gcc/x86_64-redhat-linux/
LIBRARY_PATH=/usr/lib/gcc/x86_64-redhat-linux/8/:/usr/lib/gcc/x86_64-redhat-linux/8/../../../../lib64/:/lib/../lib64/:/usr/lib/../lib64/:/usr/lib/gcc/x86_64-redhat-linux/8/../../../:/lib/:/usr/lib/
COLLECT_GCC_OPTIONS='-z' 'noexecstack' '-o' '/hello/hello' '-v' '-L/tmp/SVM-1043361363098864337' '-L/usr/lib64/graalvm/graalvm22-ce-java17/lib/static/linux-amd64/glibc' '-L/usr/lib64/graalvm/graalvm22-ce-java17/lib/svm/clibraries/linux-amd64' '-mtune=generic' '-march=x86-64'
 /usr/libexec/gcc/x86_64-redhat-linux/8/collect2 -plugin /usr/libexec/gcc/x86_64-redhat-linux/8/liblto_plugin.so -plugin-opt=/usr/libexec/gcc/x86_64-redhat-linux/8/lto-wrapper -plugin-opt=-fresolution=/tmp/cc6veW9s.res -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lc -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s --build-id --no-add-needed --eh-frame-hdr --hash-style=gnu -m elf_x86_64 -dynamic-linker /lib64/ld-linux-x86-64.so.2 -o /hello/hello -z noexecstack /usr/lib/gcc/x86_64-redhat-linux/8/../../../../lib64/crt1.o /usr/lib/gcc/x86_64-redhat-linux/8/../../../../lib64/crti.o /usr/lib/gcc/x86_64-redhat-linux/8/crtbegin.o -L/tmp/SVM-1043361363098864337 -L/usr/lib64/graalvm/graalvm22-ce-java17/lib/static/linux-amd64/glibc -L/usr/lib64/graalvm/graalvm22-ce-java17/lib/svm/clibraries/linux-amd64 -L/usr/lib/gcc/x86_64-redhat-linux/8 -L/usr/lib/gcc/x86_64-redhat-linux/8/../../../../lib64 -L/lib/../lib64 -L/usr/lib/../lib64 -L/usr/lib/gcc/x86_64-redhat-linux/8/../../.. --gc-sections --dynamic-list /tmp/SVM-1043361363098864337/exported_symbols.list --exclude-libs ALL -x hello.o /usr/lib64/graalvm/graalvm22-ce-java17/lib/svm/clibraries/linux-amd64/liblibchelper.a /usr/lib64/graalvm/graalvm22-ce-java17/lib/static/linux-amd64/glibc/libnet.a /usr/lib64/graalvm/graalvm22-ce-java17/lib/static/linux-amd64/glibc/libextnet.a /usr/lib64/graalvm/graalvm22-ce-java17/lib/static/linux-amd64/glibc/libnio.a /usr/lib64/graalvm/graalvm22-ce-java17/lib/static/linux-amd64/glibc/libjava.a /usr/lib64/graalvm/graalvm22-ce-java17/lib/static/linux-amd64/glibc/libfdlibm.a /usr/lib64/graalvm/graalvm22-ce-java17/lib/static/linux-amd64/glibc/libzip.a /usr/lib64/graalvm/graalvm22-ce-java17/lib/svm/clibraries/linux-amd64/libjvm.a -lpthread -ldl -lz -lrt -lgcc --as-needed -lgcc_s --no-as-needed -lc -lgcc --as-needed -lgcc_s --no-as-needed /usr/lib/gcc/x86_64-redhat-linux/8/crtend.o /usr/lib/gcc/x86_64-redhat-linux/8/../../../../lib64/crtn.o
hello.o:(.data+0x210): undefined reference to `Java_java_lang_PanwHooksNs_HookArgs0'
collect2: error: ld returned 1 exit status
	at com.oracle.svm.hosted.image.NativeImageViaCC.handleLinkerFailure(NativeImageViaCC.java:505)
	at com.oracle.svm.hosted.image.NativeImageViaCC.write(NativeImageViaCC.java:452)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:695)
	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:515)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:407)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:585)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:615)
-----------------------------------------------------------------------------------------------
            3.5s (7.9% of total time) in 25 GCs | Peak RSS: 4.84GB | CPU load: 8.32
===============================================================================================
Failed generating 'hello' after 43.9s.
Error: Image build request failed with exit status 1
```

**Comment by oubidar-Abderrahim** [comment]
Hi, I tried your script locally on my Ubuntu 18.04 amd64 machine and was able to successfully generate the native image. 

```
> nano script.sh
> sudo chmod +x ./script.sh
[sudo] password for abderrahim: 
> ./script.sh
Unable to find image 'ghcr.io/graalvm/native-image:22' locally
22: Pulling from graalvm/native-image
e4430e06691f: Pull complete 
f5ba15352c52: Pull complete 
824c05a6c6f1: Pull complete 
Digest: sha256:9788c780e1d2b0d3e224dbf3ca............21b21953e2df332a12e90d43d
Status: Downloaded newer image for ghcr.io/graalvm/native-image:22
========================================================================================================================
GraalVM Native Image: Generating 'hello' (executable)...
========================================================================================================================
[1/7] Initializing...                                                                                    (2.1s @ 0.20GB)
 Version info: 'GraalVM 22.1.0 Java 17 CE'
 C compiler: gcc (redhat, x86_64, 8.5.0)
 Garbage collector: Serial GC
[2/7] Performing analysis...  [**************]                                                          (13.8s @ 2.81GB)
   5,582 (85.82%) of  6,504 classes reachable
   7,476 (54.98%) of 13,598 fields reachable
  26,281 (55.24%) of 47,576 methods reachable
     350 classes,    96 fields, and 1,012 methods registered for reflection
      61 classes,    67 fields, and    54 methods registered for JNI access
[3/7] Building universe...                                                                               (2.1s @ 1.00GB)
[4/7] Parsing methods...      [*]                                                                        (0.8s @ 1.59GB)
[5/7] Inlining methods...     [****]                                                                     (1.2s @ 1.26GB)
[6/7] Compiling methods...    [***]                                                                     (10.0s @ 2.07GB)
[7/7] Creating image...                                                                                  (2.1s @ 2.67GB)
  11.72MB (43.35%) for code area:   16,826 compilation units
  12.85MB (47.54%) for image heap:   3,782 classes and 171,448 objects
   2.46MB ( 9.11%) for other data
  27.04MB in total
------------------------------------------------------------------------------------------------------------------------
Top 10 packages in code area:                               Top 10 object types in image heap:
   1.50MB sun.security.ssl                                     2.42MB byte[] for code metadata
 849.24KB java.util                                            1.68MB byte[] for general heap data
 707.50KB com.sun.crypto.provider                              1.49MB java.lang.String
 473.79KB sun.security.x509                                    1.24MB java.lang.Class
 408.31KB java.lang.invoke                                     1.02MB byte[] for java.lang.String
 370.85KB java.lang                                          436.09KB com.oracle.svm.core.hub.DynamicHubCompanion
 339.99KB com.oracle.svm.core.reflect                        430.59KB java.util.HashMap$Node
 306.08KB java.io                                            297.41KB java.lang.String[]
 283.24KB java.text                                          279.61KB java.util.concurrent.ConcurrentHashMap$Node
 280.86KB sun.security.provider.certpath                     221.88KB byte[] for reflection metadata
      ... 177 additional packages                                 ... 1531 additional object types
                                           (use GraalVM Dashboard to see all)
------------------------------------------------------------------------------------------------------------------------
                        2.7s (7.9% of total time) in 23 GCs | Peak RSS: 5.41GB | CPU load: 8.61
------------------------------------------------------------------------------------------------------------------------
Produced artifacts:
 /hello/hello (executable)
 /hello/hello.build_artifacts.txt
========================================================================================================================
Finished generating 'hello' in 34.3s.
> cat script.sh
#! /usr/bin/env bash

cat << EOF > Hello.java
public class Hello {
  public static void main(String[] args) {
    System.out.println("hello!");
  }
}
EOF

javac Hello.java

docker run -v $(pwd):/hello  --rm  --workdir /hello  -ti ghcr.io/graalvm/native-image:22   -cp . Hello  --enable-https
```
What OS you're using? could you verify if this is still an issue for you?

**Comment by rafaeldff** [comment]
I was surprised to see that the issue was not trivially reproduced, so I dug deeper and the most likely culprit is the corporate EDR/UEM agent called Cortex XDR, which apparently hooks into java processes. @oubidar-Abderrahim closing the ticket now, thanks for taking the time.
